# Server port is arbitrary
spring.datasource.url=jdbc:postgresql://localhost:5000/critter
spring.datasource.username=admin
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=true
# Data Source Setup
# Note: Users must create a H2 db that they will reference here, create a user that has access to it on localhost
#       and provide the credentials below to access it

# uncomment the below lines to view sql output in console

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

spring.properties.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect
